[project]
name = 'clarity-examples-official'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.borrowing-protocol-example]
path = 'contracts/borrowing-protocol-example.clar'
clarity_version = 3
epoch = 3.1

[contracts.yield-calculator-example]
path = 'contracts/yield-calculator-example.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
